// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_message_2eproto__INCLUDED
#define PROTOBUF_message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace gocnn {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_message_2eproto();
void protobuf_AssignDesc_message_2eproto();
void protobuf_ShutdownFile_message_2eproto();

class RequestV1;
class RequestV2;
class ResponseV1;
class ResponseV2;

// ===================================================================

class RequestV1 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gocnn.RequestV1) */ {
 public:
  RequestV1();
  virtual ~RequestV1();

  RequestV1(const RequestV1& from);

  inline RequestV1& operator=(const RequestV1& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestV1& default_instance();

  void Swap(RequestV1* other);

  // implements Message ----------------------------------------------

  inline RequestV1* New() const { return New(NULL); }

  RequestV1* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RequestV1& from);
  void MergeFrom(const RequestV1& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RequestV1* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 board_size = 1;
  void clear_board_size();
  static const int kBoardSizeFieldNumber = 1;
  ::google::protobuf::int32 board_size() const;
  void set_board_size(::google::protobuf::int32 value);

  // repeated bool board_state = 2;
  int board_state_size() const;
  void clear_board_state();
  static const int kBoardStateFieldNumber = 2;
  bool board_state(int index) const;
  void set_board_state(int index, bool value);
  void add_board_state(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      board_state() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_board_state();

  // repeated bool our_group_lib1 = 3;
  int our_group_lib1_size() const;
  void clear_our_group_lib1();
  static const int kOurGroupLib1FieldNumber = 3;
  bool our_group_lib1(int index) const;
  void set_our_group_lib1(int index, bool value);
  void add_our_group_lib1(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      our_group_lib1() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_our_group_lib1();

  // repeated bool our_group_lib2 = 4;
  int our_group_lib2_size() const;
  void clear_our_group_lib2();
  static const int kOurGroupLib2FieldNumber = 4;
  bool our_group_lib2(int index) const;
  void set_our_group_lib2(int index, bool value);
  void add_our_group_lib2(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      our_group_lib2() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_our_group_lib2();

  // repeated bool our_group_lib3_plus = 5;
  int our_group_lib3_plus_size() const;
  void clear_our_group_lib3_plus();
  static const int kOurGroupLib3PlusFieldNumber = 5;
  bool our_group_lib3_plus(int index) const;
  void set_our_group_lib3_plus(int index, bool value);
  void add_our_group_lib3_plus(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      our_group_lib3_plus() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_our_group_lib3_plus();

  // repeated bool oppo_group_lib1 = 6;
  int oppo_group_lib1_size() const;
  void clear_oppo_group_lib1();
  static const int kOppoGroupLib1FieldNumber = 6;
  bool oppo_group_lib1(int index) const;
  void set_oppo_group_lib1(int index, bool value);
  void add_oppo_group_lib1(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      oppo_group_lib1() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_oppo_group_lib1();

  // repeated bool oppo_group_lib2 = 7;
  int oppo_group_lib2_size() const;
  void clear_oppo_group_lib2();
  static const int kOppoGroupLib2FieldNumber = 7;
  bool oppo_group_lib2(int index) const;
  void set_oppo_group_lib2(int index, bool value);
  void add_oppo_group_lib2(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      oppo_group_lib2() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_oppo_group_lib2();

  // repeated bool oppo_group_lib3_plus = 8;
  int oppo_group_lib3_plus_size() const;
  void clear_oppo_group_lib3_plus();
  static const int kOppoGroupLib3PlusFieldNumber = 8;
  bool oppo_group_lib3_plus(int index) const;
  void set_oppo_group_lib3_plus(int index, bool value);
  void add_oppo_group_lib3_plus(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      oppo_group_lib3_plus() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_oppo_group_lib3_plus();

  // @@protoc_insertion_point(class_scope:gocnn.RequestV1)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedField< bool > board_state_;
  mutable int _board_state_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > our_group_lib1_;
  mutable int _our_group_lib1_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > our_group_lib2_;
  mutable int _our_group_lib2_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > our_group_lib3_plus_;
  mutable int _our_group_lib3_plus_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > oppo_group_lib1_;
  mutable int _oppo_group_lib1_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > oppo_group_lib2_;
  mutable int _oppo_group_lib2_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > oppo_group_lib3_plus_;
  mutable int _oppo_group_lib3_plus_cached_byte_size_;
  ::google::protobuf::int32 board_size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static RequestV1* default_instance_;
};
// -------------------------------------------------------------------

class ResponseV1 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gocnn.ResponseV1) */ {
 public:
  ResponseV1();
  virtual ~ResponseV1();

  ResponseV1(const ResponseV1& from);

  inline ResponseV1& operator=(const ResponseV1& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResponseV1& default_instance();

  void Swap(ResponseV1* other);

  // implements Message ----------------------------------------------

  inline ResponseV1* New() const { return New(NULL); }

  ResponseV1* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ResponseV1& from);
  void MergeFrom(const ResponseV1& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ResponseV1* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 board_size = 1;
  void clear_board_size();
  static const int kBoardSizeFieldNumber = 1;
  ::google::protobuf::int32 board_size() const;
  void set_board_size(::google::protobuf::int32 value);

  // repeated float possibility = 2;
  int possibility_size() const;
  void clear_possibility();
  static const int kPossibilityFieldNumber = 2;
  float possibility(int index) const;
  void set_possibility(int index, float value);
  void add_possibility(float value);
  const ::google::protobuf::RepeatedField< float >&
      possibility() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_possibility();

  // @@protoc_insertion_point(class_scope:gocnn.ResponseV1)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedField< float > possibility_;
  mutable int _possibility_cached_byte_size_;
  ::google::protobuf::int32 board_size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static ResponseV1* default_instance_;
};
// -------------------------------------------------------------------

class RequestV2 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gocnn.RequestV2) */ {
 public:
  RequestV2();
  virtual ~RequestV2();

  RequestV2(const RequestV2& from);

  inline RequestV2& operator=(const RequestV2& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestV2& default_instance();

  void Swap(RequestV2* other);

  // implements Message ----------------------------------------------

  inline RequestV2* New() const { return New(NULL); }

  RequestV2* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RequestV2& from);
  void MergeFrom(const RequestV2& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RequestV2* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 board_size = 1;
  void clear_board_size();
  static const int kBoardSizeFieldNumber = 1;
  ::google::protobuf::int32 board_size() const;
  void set_board_size(::google::protobuf::int32 value);

  // repeated bool board_state = 2;
  int board_state_size() const;
  void clear_board_state();
  static const int kBoardStateFieldNumber = 2;
  bool board_state(int index) const;
  void set_board_state(int index, bool value);
  void add_board_state(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      board_state() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_board_state();

  // repeated bool our_group_lib1 = 3;
  int our_group_lib1_size() const;
  void clear_our_group_lib1();
  static const int kOurGroupLib1FieldNumber = 3;
  bool our_group_lib1(int index) const;
  void set_our_group_lib1(int index, bool value);
  void add_our_group_lib1(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      our_group_lib1() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_our_group_lib1();

  // repeated bool our_group_lib2 = 4;
  int our_group_lib2_size() const;
  void clear_our_group_lib2();
  static const int kOurGroupLib2FieldNumber = 4;
  bool our_group_lib2(int index) const;
  void set_our_group_lib2(int index, bool value);
  void add_our_group_lib2(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      our_group_lib2() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_our_group_lib2();

  // repeated bool our_group_lib3 = 5;
  int our_group_lib3_size() const;
  void clear_our_group_lib3();
  static const int kOurGroupLib3FieldNumber = 5;
  bool our_group_lib3(int index) const;
  void set_our_group_lib3(int index, bool value);
  void add_our_group_lib3(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      our_group_lib3() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_our_group_lib3();

  // repeated bool our_group_lib4_plus = 6;
  int our_group_lib4_plus_size() const;
  void clear_our_group_lib4_plus();
  static const int kOurGroupLib4PlusFieldNumber = 6;
  bool our_group_lib4_plus(int index) const;
  void set_our_group_lib4_plus(int index, bool value);
  void add_our_group_lib4_plus(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      our_group_lib4_plus() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_our_group_lib4_plus();

  // repeated bool oppo_group_lib1 = 7;
  int oppo_group_lib1_size() const;
  void clear_oppo_group_lib1();
  static const int kOppoGroupLib1FieldNumber = 7;
  bool oppo_group_lib1(int index) const;
  void set_oppo_group_lib1(int index, bool value);
  void add_oppo_group_lib1(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      oppo_group_lib1() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_oppo_group_lib1();

  // repeated bool oppo_group_lib2 = 8;
  int oppo_group_lib2_size() const;
  void clear_oppo_group_lib2();
  static const int kOppoGroupLib2FieldNumber = 8;
  bool oppo_group_lib2(int index) const;
  void set_oppo_group_lib2(int index, bool value);
  void add_oppo_group_lib2(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      oppo_group_lib2() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_oppo_group_lib2();

  // repeated bool oppo_group_lib3 = 9;
  int oppo_group_lib3_size() const;
  void clear_oppo_group_lib3();
  static const int kOppoGroupLib3FieldNumber = 9;
  bool oppo_group_lib3(int index) const;
  void set_oppo_group_lib3(int index, bool value);
  void add_oppo_group_lib3(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      oppo_group_lib3() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_oppo_group_lib3();

  // repeated bool oppo_group_lib4_plus = 10;
  int oppo_group_lib4_plus_size() const;
  void clear_oppo_group_lib4_plus();
  static const int kOppoGroupLib4PlusFieldNumber = 10;
  bool oppo_group_lib4_plus(int index) const;
  void set_oppo_group_lib4_plus(int index, bool value);
  void add_oppo_group_lib4_plus(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      oppo_group_lib4_plus() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_oppo_group_lib4_plus();

  // repeated bool all_ones = 11;
  int all_ones_size() const;
  void clear_all_ones();
  static const int kAllOnesFieldNumber = 11;
  bool all_ones(int index) const;
  void set_all_ones(int index, bool value);
  void add_all_ones(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      all_ones() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_all_ones();

  // repeated bool our_true_eye = 12;
  int our_true_eye_size() const;
  void clear_our_true_eye();
  static const int kOurTrueEyeFieldNumber = 12;
  bool our_true_eye(int index) const;
  void set_our_true_eye(int index, bool value);
  void add_our_true_eye(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      our_true_eye() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_our_true_eye();

  // repeated bool our_fake_eye = 13;
  int our_fake_eye_size() const;
  void clear_our_fake_eye();
  static const int kOurFakeEyeFieldNumber = 13;
  bool our_fake_eye(int index) const;
  void set_our_fake_eye(int index, bool value);
  void add_our_fake_eye(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      our_fake_eye() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_our_fake_eye();

  // repeated bool our_semi_eye = 14;
  int our_semi_eye_size() const;
  void clear_our_semi_eye();
  static const int kOurSemiEyeFieldNumber = 14;
  bool our_semi_eye(int index) const;
  void set_our_semi_eye(int index, bool value);
  void add_our_semi_eye(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      our_semi_eye() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_our_semi_eye();

  // repeated bool oppo_true_eye = 15;
  int oppo_true_eye_size() const;
  void clear_oppo_true_eye();
  static const int kOppoTrueEyeFieldNumber = 15;
  bool oppo_true_eye(int index) const;
  void set_oppo_true_eye(int index, bool value);
  void add_oppo_true_eye(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      oppo_true_eye() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_oppo_true_eye();

  // repeated bool oppo_fake_eye = 16;
  int oppo_fake_eye_size() const;
  void clear_oppo_fake_eye();
  static const int kOppoFakeEyeFieldNumber = 16;
  bool oppo_fake_eye(int index) const;
  void set_oppo_fake_eye(int index, bool value);
  void add_oppo_fake_eye(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      oppo_fake_eye() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_oppo_fake_eye();

  // repeated bool oppo_semi_eye = 17;
  int oppo_semi_eye_size() const;
  void clear_oppo_semi_eye();
  static const int kOppoSemiEyeFieldNumber = 17;
  bool oppo_semi_eye(int index) const;
  void set_oppo_semi_eye(int index, bool value);
  void add_oppo_semi_eye(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      oppo_semi_eye() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_oppo_semi_eye();

  // repeated bool all_zeros = 18;
  int all_zeros_size() const;
  void clear_all_zeros();
  static const int kAllZerosFieldNumber = 18;
  bool all_zeros(int index) const;
  void set_all_zeros(int index, bool value);
  void add_all_zeros(bool value);
  const ::google::protobuf::RepeatedField< bool >&
      all_zeros() const;
  ::google::protobuf::RepeatedField< bool >*
      mutable_all_zeros();

  // @@protoc_insertion_point(class_scope:gocnn.RequestV2)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedField< bool > board_state_;
  mutable int _board_state_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > our_group_lib1_;
  mutable int _our_group_lib1_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > our_group_lib2_;
  mutable int _our_group_lib2_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > our_group_lib3_;
  mutable int _our_group_lib3_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > our_group_lib4_plus_;
  mutable int _our_group_lib4_plus_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > oppo_group_lib1_;
  mutable int _oppo_group_lib1_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > oppo_group_lib2_;
  mutable int _oppo_group_lib2_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > oppo_group_lib3_;
  mutable int _oppo_group_lib3_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > oppo_group_lib4_plus_;
  mutable int _oppo_group_lib4_plus_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > all_ones_;
  mutable int _all_ones_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > our_true_eye_;
  mutable int _our_true_eye_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > our_fake_eye_;
  mutable int _our_fake_eye_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > our_semi_eye_;
  mutable int _our_semi_eye_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > oppo_true_eye_;
  mutable int _oppo_true_eye_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > oppo_fake_eye_;
  mutable int _oppo_fake_eye_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > oppo_semi_eye_;
  mutable int _oppo_semi_eye_cached_byte_size_;
  ::google::protobuf::RepeatedField< bool > all_zeros_;
  mutable int _all_zeros_cached_byte_size_;
  ::google::protobuf::int32 board_size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static RequestV2* default_instance_;
};
// -------------------------------------------------------------------

class ResponseV2 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gocnn.ResponseV2) */ {
 public:
  ResponseV2();
  virtual ~ResponseV2();

  ResponseV2(const ResponseV2& from);

  inline ResponseV2& operator=(const ResponseV2& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResponseV2& default_instance();

  void Swap(ResponseV2* other);

  // implements Message ----------------------------------------------

  inline ResponseV2* New() const { return New(NULL); }

  ResponseV2* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ResponseV2& from);
  void MergeFrom(const ResponseV2& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ResponseV2* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 board_size = 1;
  void clear_board_size();
  static const int kBoardSizeFieldNumber = 1;
  ::google::protobuf::int32 board_size() const;
  void set_board_size(::google::protobuf::int32 value);

  // repeated float possibility = 2;
  int possibility_size() const;
  void clear_possibility();
  static const int kPossibilityFieldNumber = 2;
  float possibility(int index) const;
  void set_possibility(int index, float value);
  void add_possibility(float value);
  const ::google::protobuf::RepeatedField< float >&
      possibility() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_possibility();

  // @@protoc_insertion_point(class_scope:gocnn.ResponseV2)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedField< float > possibility_;
  mutable int _possibility_cached_byte_size_;
  ::google::protobuf::int32 board_size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static ResponseV2* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// RequestV1

// optional int32 board_size = 1;
inline void RequestV1::clear_board_size() {
  board_size_ = 0;
}
inline ::google::protobuf::int32 RequestV1::board_size() const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV1.board_size)
  return board_size_;
}
inline void RequestV1::set_board_size(::google::protobuf::int32 value) {
  
  board_size_ = value;
  // @@protoc_insertion_point(field_set:gocnn.RequestV1.board_size)
}

// repeated bool board_state = 2;
inline int RequestV1::board_state_size() const {
  return board_state_.size();
}
inline void RequestV1::clear_board_state() {
  board_state_.Clear();
}
inline bool RequestV1::board_state(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV1.board_state)
  return board_state_.Get(index);
}
inline void RequestV1::set_board_state(int index, bool value) {
  board_state_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV1.board_state)
}
inline void RequestV1::add_board_state(bool value) {
  board_state_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV1.board_state)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV1::board_state() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV1.board_state)
  return board_state_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV1::mutable_board_state() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV1.board_state)
  return &board_state_;
}

// repeated bool our_group_lib1 = 3;
inline int RequestV1::our_group_lib1_size() const {
  return our_group_lib1_.size();
}
inline void RequestV1::clear_our_group_lib1() {
  our_group_lib1_.Clear();
}
inline bool RequestV1::our_group_lib1(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV1.our_group_lib1)
  return our_group_lib1_.Get(index);
}
inline void RequestV1::set_our_group_lib1(int index, bool value) {
  our_group_lib1_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV1.our_group_lib1)
}
inline void RequestV1::add_our_group_lib1(bool value) {
  our_group_lib1_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV1.our_group_lib1)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV1::our_group_lib1() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV1.our_group_lib1)
  return our_group_lib1_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV1::mutable_our_group_lib1() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV1.our_group_lib1)
  return &our_group_lib1_;
}

// repeated bool our_group_lib2 = 4;
inline int RequestV1::our_group_lib2_size() const {
  return our_group_lib2_.size();
}
inline void RequestV1::clear_our_group_lib2() {
  our_group_lib2_.Clear();
}
inline bool RequestV1::our_group_lib2(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV1.our_group_lib2)
  return our_group_lib2_.Get(index);
}
inline void RequestV1::set_our_group_lib2(int index, bool value) {
  our_group_lib2_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV1.our_group_lib2)
}
inline void RequestV1::add_our_group_lib2(bool value) {
  our_group_lib2_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV1.our_group_lib2)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV1::our_group_lib2() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV1.our_group_lib2)
  return our_group_lib2_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV1::mutable_our_group_lib2() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV1.our_group_lib2)
  return &our_group_lib2_;
}

// repeated bool our_group_lib3_plus = 5;
inline int RequestV1::our_group_lib3_plus_size() const {
  return our_group_lib3_plus_.size();
}
inline void RequestV1::clear_our_group_lib3_plus() {
  our_group_lib3_plus_.Clear();
}
inline bool RequestV1::our_group_lib3_plus(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV1.our_group_lib3_plus)
  return our_group_lib3_plus_.Get(index);
}
inline void RequestV1::set_our_group_lib3_plus(int index, bool value) {
  our_group_lib3_plus_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV1.our_group_lib3_plus)
}
inline void RequestV1::add_our_group_lib3_plus(bool value) {
  our_group_lib3_plus_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV1.our_group_lib3_plus)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV1::our_group_lib3_plus() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV1.our_group_lib3_plus)
  return our_group_lib3_plus_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV1::mutable_our_group_lib3_plus() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV1.our_group_lib3_plus)
  return &our_group_lib3_plus_;
}

// repeated bool oppo_group_lib1 = 6;
inline int RequestV1::oppo_group_lib1_size() const {
  return oppo_group_lib1_.size();
}
inline void RequestV1::clear_oppo_group_lib1() {
  oppo_group_lib1_.Clear();
}
inline bool RequestV1::oppo_group_lib1(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV1.oppo_group_lib1)
  return oppo_group_lib1_.Get(index);
}
inline void RequestV1::set_oppo_group_lib1(int index, bool value) {
  oppo_group_lib1_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV1.oppo_group_lib1)
}
inline void RequestV1::add_oppo_group_lib1(bool value) {
  oppo_group_lib1_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV1.oppo_group_lib1)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV1::oppo_group_lib1() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV1.oppo_group_lib1)
  return oppo_group_lib1_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV1::mutable_oppo_group_lib1() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV1.oppo_group_lib1)
  return &oppo_group_lib1_;
}

// repeated bool oppo_group_lib2 = 7;
inline int RequestV1::oppo_group_lib2_size() const {
  return oppo_group_lib2_.size();
}
inline void RequestV1::clear_oppo_group_lib2() {
  oppo_group_lib2_.Clear();
}
inline bool RequestV1::oppo_group_lib2(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV1.oppo_group_lib2)
  return oppo_group_lib2_.Get(index);
}
inline void RequestV1::set_oppo_group_lib2(int index, bool value) {
  oppo_group_lib2_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV1.oppo_group_lib2)
}
inline void RequestV1::add_oppo_group_lib2(bool value) {
  oppo_group_lib2_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV1.oppo_group_lib2)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV1::oppo_group_lib2() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV1.oppo_group_lib2)
  return oppo_group_lib2_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV1::mutable_oppo_group_lib2() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV1.oppo_group_lib2)
  return &oppo_group_lib2_;
}

// repeated bool oppo_group_lib3_plus = 8;
inline int RequestV1::oppo_group_lib3_plus_size() const {
  return oppo_group_lib3_plus_.size();
}
inline void RequestV1::clear_oppo_group_lib3_plus() {
  oppo_group_lib3_plus_.Clear();
}
inline bool RequestV1::oppo_group_lib3_plus(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV1.oppo_group_lib3_plus)
  return oppo_group_lib3_plus_.Get(index);
}
inline void RequestV1::set_oppo_group_lib3_plus(int index, bool value) {
  oppo_group_lib3_plus_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV1.oppo_group_lib3_plus)
}
inline void RequestV1::add_oppo_group_lib3_plus(bool value) {
  oppo_group_lib3_plus_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV1.oppo_group_lib3_plus)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV1::oppo_group_lib3_plus() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV1.oppo_group_lib3_plus)
  return oppo_group_lib3_plus_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV1::mutable_oppo_group_lib3_plus() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV1.oppo_group_lib3_plus)
  return &oppo_group_lib3_plus_;
}

// -------------------------------------------------------------------

// ResponseV1

// optional int32 board_size = 1;
inline void ResponseV1::clear_board_size() {
  board_size_ = 0;
}
inline ::google::protobuf::int32 ResponseV1::board_size() const {
  // @@protoc_insertion_point(field_get:gocnn.ResponseV1.board_size)
  return board_size_;
}
inline void ResponseV1::set_board_size(::google::protobuf::int32 value) {
  
  board_size_ = value;
  // @@protoc_insertion_point(field_set:gocnn.ResponseV1.board_size)
}

// repeated float possibility = 2;
inline int ResponseV1::possibility_size() const {
  return possibility_.size();
}
inline void ResponseV1::clear_possibility() {
  possibility_.Clear();
}
inline float ResponseV1::possibility(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.ResponseV1.possibility)
  return possibility_.Get(index);
}
inline void ResponseV1::set_possibility(int index, float value) {
  possibility_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.ResponseV1.possibility)
}
inline void ResponseV1::add_possibility(float value) {
  possibility_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.ResponseV1.possibility)
}
inline const ::google::protobuf::RepeatedField< float >&
ResponseV1::possibility() const {
  // @@protoc_insertion_point(field_list:gocnn.ResponseV1.possibility)
  return possibility_;
}
inline ::google::protobuf::RepeatedField< float >*
ResponseV1::mutable_possibility() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.ResponseV1.possibility)
  return &possibility_;
}

// -------------------------------------------------------------------

// RequestV2

// optional int32 board_size = 1;
inline void RequestV2::clear_board_size() {
  board_size_ = 0;
}
inline ::google::protobuf::int32 RequestV2::board_size() const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.board_size)
  return board_size_;
}
inline void RequestV2::set_board_size(::google::protobuf::int32 value) {
  
  board_size_ = value;
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.board_size)
}

// repeated bool board_state = 2;
inline int RequestV2::board_state_size() const {
  return board_state_.size();
}
inline void RequestV2::clear_board_state() {
  board_state_.Clear();
}
inline bool RequestV2::board_state(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.board_state)
  return board_state_.Get(index);
}
inline void RequestV2::set_board_state(int index, bool value) {
  board_state_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.board_state)
}
inline void RequestV2::add_board_state(bool value) {
  board_state_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.board_state)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::board_state() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.board_state)
  return board_state_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_board_state() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.board_state)
  return &board_state_;
}

// repeated bool our_group_lib1 = 3;
inline int RequestV2::our_group_lib1_size() const {
  return our_group_lib1_.size();
}
inline void RequestV2::clear_our_group_lib1() {
  our_group_lib1_.Clear();
}
inline bool RequestV2::our_group_lib1(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.our_group_lib1)
  return our_group_lib1_.Get(index);
}
inline void RequestV2::set_our_group_lib1(int index, bool value) {
  our_group_lib1_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.our_group_lib1)
}
inline void RequestV2::add_our_group_lib1(bool value) {
  our_group_lib1_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.our_group_lib1)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::our_group_lib1() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.our_group_lib1)
  return our_group_lib1_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_our_group_lib1() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.our_group_lib1)
  return &our_group_lib1_;
}

// repeated bool our_group_lib2 = 4;
inline int RequestV2::our_group_lib2_size() const {
  return our_group_lib2_.size();
}
inline void RequestV2::clear_our_group_lib2() {
  our_group_lib2_.Clear();
}
inline bool RequestV2::our_group_lib2(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.our_group_lib2)
  return our_group_lib2_.Get(index);
}
inline void RequestV2::set_our_group_lib2(int index, bool value) {
  our_group_lib2_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.our_group_lib2)
}
inline void RequestV2::add_our_group_lib2(bool value) {
  our_group_lib2_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.our_group_lib2)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::our_group_lib2() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.our_group_lib2)
  return our_group_lib2_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_our_group_lib2() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.our_group_lib2)
  return &our_group_lib2_;
}

// repeated bool our_group_lib3 = 5;
inline int RequestV2::our_group_lib3_size() const {
  return our_group_lib3_.size();
}
inline void RequestV2::clear_our_group_lib3() {
  our_group_lib3_.Clear();
}
inline bool RequestV2::our_group_lib3(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.our_group_lib3)
  return our_group_lib3_.Get(index);
}
inline void RequestV2::set_our_group_lib3(int index, bool value) {
  our_group_lib3_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.our_group_lib3)
}
inline void RequestV2::add_our_group_lib3(bool value) {
  our_group_lib3_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.our_group_lib3)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::our_group_lib3() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.our_group_lib3)
  return our_group_lib3_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_our_group_lib3() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.our_group_lib3)
  return &our_group_lib3_;
}

// repeated bool our_group_lib4_plus = 6;
inline int RequestV2::our_group_lib4_plus_size() const {
  return our_group_lib4_plus_.size();
}
inline void RequestV2::clear_our_group_lib4_plus() {
  our_group_lib4_plus_.Clear();
}
inline bool RequestV2::our_group_lib4_plus(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.our_group_lib4_plus)
  return our_group_lib4_plus_.Get(index);
}
inline void RequestV2::set_our_group_lib4_plus(int index, bool value) {
  our_group_lib4_plus_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.our_group_lib4_plus)
}
inline void RequestV2::add_our_group_lib4_plus(bool value) {
  our_group_lib4_plus_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.our_group_lib4_plus)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::our_group_lib4_plus() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.our_group_lib4_plus)
  return our_group_lib4_plus_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_our_group_lib4_plus() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.our_group_lib4_plus)
  return &our_group_lib4_plus_;
}

// repeated bool oppo_group_lib1 = 7;
inline int RequestV2::oppo_group_lib1_size() const {
  return oppo_group_lib1_.size();
}
inline void RequestV2::clear_oppo_group_lib1() {
  oppo_group_lib1_.Clear();
}
inline bool RequestV2::oppo_group_lib1(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.oppo_group_lib1)
  return oppo_group_lib1_.Get(index);
}
inline void RequestV2::set_oppo_group_lib1(int index, bool value) {
  oppo_group_lib1_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.oppo_group_lib1)
}
inline void RequestV2::add_oppo_group_lib1(bool value) {
  oppo_group_lib1_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.oppo_group_lib1)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::oppo_group_lib1() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.oppo_group_lib1)
  return oppo_group_lib1_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_oppo_group_lib1() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.oppo_group_lib1)
  return &oppo_group_lib1_;
}

// repeated bool oppo_group_lib2 = 8;
inline int RequestV2::oppo_group_lib2_size() const {
  return oppo_group_lib2_.size();
}
inline void RequestV2::clear_oppo_group_lib2() {
  oppo_group_lib2_.Clear();
}
inline bool RequestV2::oppo_group_lib2(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.oppo_group_lib2)
  return oppo_group_lib2_.Get(index);
}
inline void RequestV2::set_oppo_group_lib2(int index, bool value) {
  oppo_group_lib2_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.oppo_group_lib2)
}
inline void RequestV2::add_oppo_group_lib2(bool value) {
  oppo_group_lib2_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.oppo_group_lib2)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::oppo_group_lib2() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.oppo_group_lib2)
  return oppo_group_lib2_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_oppo_group_lib2() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.oppo_group_lib2)
  return &oppo_group_lib2_;
}

// repeated bool oppo_group_lib3 = 9;
inline int RequestV2::oppo_group_lib3_size() const {
  return oppo_group_lib3_.size();
}
inline void RequestV2::clear_oppo_group_lib3() {
  oppo_group_lib3_.Clear();
}
inline bool RequestV2::oppo_group_lib3(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.oppo_group_lib3)
  return oppo_group_lib3_.Get(index);
}
inline void RequestV2::set_oppo_group_lib3(int index, bool value) {
  oppo_group_lib3_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.oppo_group_lib3)
}
inline void RequestV2::add_oppo_group_lib3(bool value) {
  oppo_group_lib3_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.oppo_group_lib3)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::oppo_group_lib3() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.oppo_group_lib3)
  return oppo_group_lib3_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_oppo_group_lib3() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.oppo_group_lib3)
  return &oppo_group_lib3_;
}

// repeated bool oppo_group_lib4_plus = 10;
inline int RequestV2::oppo_group_lib4_plus_size() const {
  return oppo_group_lib4_plus_.size();
}
inline void RequestV2::clear_oppo_group_lib4_plus() {
  oppo_group_lib4_plus_.Clear();
}
inline bool RequestV2::oppo_group_lib4_plus(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.oppo_group_lib4_plus)
  return oppo_group_lib4_plus_.Get(index);
}
inline void RequestV2::set_oppo_group_lib4_plus(int index, bool value) {
  oppo_group_lib4_plus_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.oppo_group_lib4_plus)
}
inline void RequestV2::add_oppo_group_lib4_plus(bool value) {
  oppo_group_lib4_plus_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.oppo_group_lib4_plus)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::oppo_group_lib4_plus() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.oppo_group_lib4_plus)
  return oppo_group_lib4_plus_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_oppo_group_lib4_plus() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.oppo_group_lib4_plus)
  return &oppo_group_lib4_plus_;
}

// repeated bool all_ones = 11;
inline int RequestV2::all_ones_size() const {
  return all_ones_.size();
}
inline void RequestV2::clear_all_ones() {
  all_ones_.Clear();
}
inline bool RequestV2::all_ones(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.all_ones)
  return all_ones_.Get(index);
}
inline void RequestV2::set_all_ones(int index, bool value) {
  all_ones_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.all_ones)
}
inline void RequestV2::add_all_ones(bool value) {
  all_ones_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.all_ones)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::all_ones() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.all_ones)
  return all_ones_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_all_ones() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.all_ones)
  return &all_ones_;
}

// repeated bool our_true_eye = 12;
inline int RequestV2::our_true_eye_size() const {
  return our_true_eye_.size();
}
inline void RequestV2::clear_our_true_eye() {
  our_true_eye_.Clear();
}
inline bool RequestV2::our_true_eye(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.our_true_eye)
  return our_true_eye_.Get(index);
}
inline void RequestV2::set_our_true_eye(int index, bool value) {
  our_true_eye_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.our_true_eye)
}
inline void RequestV2::add_our_true_eye(bool value) {
  our_true_eye_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.our_true_eye)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::our_true_eye() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.our_true_eye)
  return our_true_eye_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_our_true_eye() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.our_true_eye)
  return &our_true_eye_;
}

// repeated bool our_fake_eye = 13;
inline int RequestV2::our_fake_eye_size() const {
  return our_fake_eye_.size();
}
inline void RequestV2::clear_our_fake_eye() {
  our_fake_eye_.Clear();
}
inline bool RequestV2::our_fake_eye(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.our_fake_eye)
  return our_fake_eye_.Get(index);
}
inline void RequestV2::set_our_fake_eye(int index, bool value) {
  our_fake_eye_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.our_fake_eye)
}
inline void RequestV2::add_our_fake_eye(bool value) {
  our_fake_eye_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.our_fake_eye)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::our_fake_eye() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.our_fake_eye)
  return our_fake_eye_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_our_fake_eye() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.our_fake_eye)
  return &our_fake_eye_;
}

// repeated bool our_semi_eye = 14;
inline int RequestV2::our_semi_eye_size() const {
  return our_semi_eye_.size();
}
inline void RequestV2::clear_our_semi_eye() {
  our_semi_eye_.Clear();
}
inline bool RequestV2::our_semi_eye(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.our_semi_eye)
  return our_semi_eye_.Get(index);
}
inline void RequestV2::set_our_semi_eye(int index, bool value) {
  our_semi_eye_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.our_semi_eye)
}
inline void RequestV2::add_our_semi_eye(bool value) {
  our_semi_eye_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.our_semi_eye)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::our_semi_eye() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.our_semi_eye)
  return our_semi_eye_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_our_semi_eye() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.our_semi_eye)
  return &our_semi_eye_;
}

// repeated bool oppo_true_eye = 15;
inline int RequestV2::oppo_true_eye_size() const {
  return oppo_true_eye_.size();
}
inline void RequestV2::clear_oppo_true_eye() {
  oppo_true_eye_.Clear();
}
inline bool RequestV2::oppo_true_eye(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.oppo_true_eye)
  return oppo_true_eye_.Get(index);
}
inline void RequestV2::set_oppo_true_eye(int index, bool value) {
  oppo_true_eye_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.oppo_true_eye)
}
inline void RequestV2::add_oppo_true_eye(bool value) {
  oppo_true_eye_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.oppo_true_eye)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::oppo_true_eye() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.oppo_true_eye)
  return oppo_true_eye_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_oppo_true_eye() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.oppo_true_eye)
  return &oppo_true_eye_;
}

// repeated bool oppo_fake_eye = 16;
inline int RequestV2::oppo_fake_eye_size() const {
  return oppo_fake_eye_.size();
}
inline void RequestV2::clear_oppo_fake_eye() {
  oppo_fake_eye_.Clear();
}
inline bool RequestV2::oppo_fake_eye(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.oppo_fake_eye)
  return oppo_fake_eye_.Get(index);
}
inline void RequestV2::set_oppo_fake_eye(int index, bool value) {
  oppo_fake_eye_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.oppo_fake_eye)
}
inline void RequestV2::add_oppo_fake_eye(bool value) {
  oppo_fake_eye_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.oppo_fake_eye)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::oppo_fake_eye() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.oppo_fake_eye)
  return oppo_fake_eye_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_oppo_fake_eye() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.oppo_fake_eye)
  return &oppo_fake_eye_;
}

// repeated bool oppo_semi_eye = 17;
inline int RequestV2::oppo_semi_eye_size() const {
  return oppo_semi_eye_.size();
}
inline void RequestV2::clear_oppo_semi_eye() {
  oppo_semi_eye_.Clear();
}
inline bool RequestV2::oppo_semi_eye(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.oppo_semi_eye)
  return oppo_semi_eye_.Get(index);
}
inline void RequestV2::set_oppo_semi_eye(int index, bool value) {
  oppo_semi_eye_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.oppo_semi_eye)
}
inline void RequestV2::add_oppo_semi_eye(bool value) {
  oppo_semi_eye_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.oppo_semi_eye)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::oppo_semi_eye() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.oppo_semi_eye)
  return oppo_semi_eye_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_oppo_semi_eye() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.oppo_semi_eye)
  return &oppo_semi_eye_;
}

// repeated bool all_zeros = 18;
inline int RequestV2::all_zeros_size() const {
  return all_zeros_.size();
}
inline void RequestV2::clear_all_zeros() {
  all_zeros_.Clear();
}
inline bool RequestV2::all_zeros(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.RequestV2.all_zeros)
  return all_zeros_.Get(index);
}
inline void RequestV2::set_all_zeros(int index, bool value) {
  all_zeros_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.RequestV2.all_zeros)
}
inline void RequestV2::add_all_zeros(bool value) {
  all_zeros_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.RequestV2.all_zeros)
}
inline const ::google::protobuf::RepeatedField< bool >&
RequestV2::all_zeros() const {
  // @@protoc_insertion_point(field_list:gocnn.RequestV2.all_zeros)
  return all_zeros_;
}
inline ::google::protobuf::RepeatedField< bool >*
RequestV2::mutable_all_zeros() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.RequestV2.all_zeros)
  return &all_zeros_;
}

// -------------------------------------------------------------------

// ResponseV2

// optional int32 board_size = 1;
inline void ResponseV2::clear_board_size() {
  board_size_ = 0;
}
inline ::google::protobuf::int32 ResponseV2::board_size() const {
  // @@protoc_insertion_point(field_get:gocnn.ResponseV2.board_size)
  return board_size_;
}
inline void ResponseV2::set_board_size(::google::protobuf::int32 value) {
  
  board_size_ = value;
  // @@protoc_insertion_point(field_set:gocnn.ResponseV2.board_size)
}

// repeated float possibility = 2;
inline int ResponseV2::possibility_size() const {
  return possibility_.size();
}
inline void ResponseV2::clear_possibility() {
  possibility_.Clear();
}
inline float ResponseV2::possibility(int index) const {
  // @@protoc_insertion_point(field_get:gocnn.ResponseV2.possibility)
  return possibility_.Get(index);
}
inline void ResponseV2::set_possibility(int index, float value) {
  possibility_.Set(index, value);
  // @@protoc_insertion_point(field_set:gocnn.ResponseV2.possibility)
}
inline void ResponseV2::add_possibility(float value) {
  possibility_.Add(value);
  // @@protoc_insertion_point(field_add:gocnn.ResponseV2.possibility)
}
inline const ::google::protobuf::RepeatedField< float >&
ResponseV2::possibility() const {
  // @@protoc_insertion_point(field_list:gocnn.ResponseV2.possibility)
  return possibility_;
}
inline ::google::protobuf::RepeatedField< float >*
ResponseV2::mutable_possibility() {
  // @@protoc_insertion_point(field_mutable_list:gocnn.ResponseV2.possibility)
  return &possibility_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace gocnn

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_2eproto__INCLUDED
